/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Root
         * @description Root endpoint with API information.
         */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mentions
         * @description Get paginated list of company mentions.
         *
         *     Filters:
         *     - ceo_id: Filter by specific CEO
         *     - company_ticker: Filter by mentioned company ticker
         *     - sentiment: Filter by sentiment (positive/negative/neutral)
         */
        get: operations["get_mentions_api_mentions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentions/ceo/{ceo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ceo Mentions
         * @description Get all mentions by a specific CEO.
         */
        get: operations["get_ceo_mentions_api_mentions_ceo__ceo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentions/company/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Company Mentions
         * @description Get all mentions of a specific company by ticker.
         */
        get: operations["get_company_mentions_api_mentions_company__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sentiment/summary/{ceo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sentiment Summary
         * @description Get sentiment breakdown for a specific CEO.
         */
        get: operations["get_sentiment_summary_api_sentiment_summary__ceo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ceos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ceos
         * @description Get list of all tracked CEOs.
         */
        get: operations["get_ceos_api_ceos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ceos/{ceo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ceo
         * @description Get details of a specific CEO.
         */
        get: operations["get_ceo_api_ceos__ceo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Companies
         * @description Get list of all companies.
         */
        get: operations["get_companies_api_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Company
         * @description Get details of a specific company.
         */
        get: operations["get_company_api_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/ticker/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Company By Ticker
         * @description Get a company by its ticker symbol.
         */
        get: operations["get_company_by_ticker_api_companies_ticker__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Stats
         * @description Get overall dashboard statistics.
         */
        get: operations["get_dashboard_stats_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Timeline
         * @description Get chronological feed of mentions.
         */
        get: operations["get_timeline_api_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/sentiment/{sentiment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sentiment Companies
         * @description Get companies mentioned with specific sentiment.
         */
        get: operations["get_sentiment_companies_api_dashboard_sentiment__sentiment__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Text
         * @description Manually ingest text for analysis.
         *
         *     This endpoint allows manual submission of text (e.g., CEO quotes, press releases)
         *     for NER and sentiment analysis.
         */
        post: operations["ingest_text_api_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Ingestion
         * @description Test endpoint that ingests a sample text.
         */
        post: operations["test_ingestion_api_ingest_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ingestion Status
         * @description Get ingestion status statistics.
         */
        get: operations["get_ingestion_status_api_ingest_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feed Config
         * @description Get all configured RSS feeds.
         *
         *     Returns a list of all RSS feed configurations.
         */
        get: operations["get_feed_config_api_feeds_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feeds Status
         * @description Get status of all RSS feeds including entry counts.
         *
         *     Returns statistics about each feed including how many entries
         *     have been processed from each source.
         */
        get: operations["get_feeds_status_api_feeds_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Feed
         * @description Manually trigger fetch for a single RSS feed.
         *
         *     This is useful for testing or immediate updates.
         *     The task runs in the background.
         */
        post: operations["trigger_feed_api_feeds_trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh All Feeds
         * @description Refresh all RSS feeds immediately.
         *
         *     Triggers background processing for all configured feeds.
         */
        post: operations["refresh_all_feeds_api_feeds_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Feed Fetch
         * @description Test endpoint to fetch and preview a single feed without saving.
         *
         *     Useful for debugging feed configuration.
         */
        post: operations["test_feed_fetch_api_feeds_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feed Statistics
         * @description Get aggregate statistics about feed ingestion.
         *
         *     Returns totals and breakdowns by provider.
         */
        get: operations["get_feed_statistics_api_feeds_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CEOResponse
         * @description Response model for a CEO.
         */
        CEOResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Company Id */
            company_id: number;
            /** Company Name */
            company_name: string;
            /** Company Ticker */
            company_ticker: string;
            /** Title */
            title: string | null;
            /** Twitter Handle */
            twitter_handle: string | null;
        };
        /**
         * CompanyResponse
         * @description Response model for a company.
         */
        CompanyResponse: {
            /** Id */
            id: number;
            /** Ticker */
            ticker: string | null;
            /** Name */
            name: string;
            /** Is Tracked */
            is_tracked: boolean;
            /** Sector */
            sector: string | null;
            /** Industry */
            industry: string | null;
        };
        /**
         * DashboardStats
         * @description Dashboard statistics model.
         */
        DashboardStats: {
            /** Total Mentions */
            total_mentions: number;
            /** Total Ceos */
            total_ceos: number;
            /** Total Companies */
            total_companies: number;
            /** Sentiment Breakdown */
            sentiment_breakdown: {
                [key: string]: number;
            };
            /** Recent Mentions */
            recent_mentions: number;
            /** Most Mentioned Companies */
            most_mentioned_companies: Record<string, never>[];
            /** Most Active Ceos */
            most_active_ceos: Record<string, never>[];
        };
        /**
         * FeedListResponse
         * @description Response model for feed list.
         */
        FeedListResponse: {
            /** Feeds */
            feeds: components["schemas"]["FeedStatusResponse"][];
            /** Total Feeds */
            total_feeds: number;
        };
        /**
         * FeedStatusResponse
         * @description Response model for feed status.
         */
        FeedStatusResponse: {
            /** Feed Key */
            feed_key: string;
            /** Name */
            name: string;
            /** Ticker */
            ticker: string;
            /** Url */
            url: string;
            /** Provider */
            provider: string;
            /** Last Fetched */
            last_fetched?: string | null;
            /** Entries Count */
            entries_count?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestRequest
         * @description Request model for manual ingestion.
         */
        IngestRequest: {
            /** Text */
            text: string;
            /** Ceo Id */
            ceo_id: number;
            /**
             * Source Type
             * @default manual
             */
            source_type: string;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * IngestResponse
         * @description Response model for ingestion results.
         */
        IngestResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Mentions Created */
            mentions_created: number;
            /** Speech Id */
            speech_id?: number | null;
        };
        /**
         * MentionListResponse
         * @description Response model for a list of mentions.
         */
        MentionListResponse: {
            /** Mentions */
            mentions: components["schemas"]["MentionResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * MentionResponse
         * @description Response model for a company mention.
         */
        MentionResponse: {
            /** Id */
            id: number;
            /** Ceo Id */
            ceo_id: number | null;
            /** Ceo Name */
            ceo_name: string;
            /** Ceo Company */
            ceo_company: string;
            /** Mentioned Company */
            mentioned_company: string;
            /** Mentioned Ticker */
            mentioned_ticker: string | null;
            /** Context */
            context: string;
            /** Sentiment */
            sentiment: string | null;
            /** Confidence */
            confidence: number | null;
            /** Relationship Type */
            relationship_type: string | null;
            /** Created At */
            created_at: string;
        };
        /**
         * RefreshFeedsResponse
         * @description Response model for refreshing all feeds.
         */
        RefreshFeedsResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Total Entries */
            total_entries?: number | null;
            /** Total Mentions */
            total_mentions?: number | null;
        };
        /**
         * TriggerFeedRequest
         * @description Request model for triggering a single feed.
         */
        TriggerFeedRequest: {
            /** Feed Key */
            feed_key: string;
        };
        /**
         * TriggerFeedResponse
         * @description Response model for feed trigger.
         */
        TriggerFeedResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
            /** Task Id */
            task_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_mentions_api_mentions_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                ceo_id?: number | null;
                company_ticker?: string | null;
                sentiment?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ceo_mentions_api_mentions_ceo__ceo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ceo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_mentions_api_mentions_company__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sentiment_summary_api_sentiment_summary__ceo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ceo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ceos_api_ceos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CEOResponse"][];
                };
            };
        };
    };
    get_ceo_api_ceos__ceo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ceo_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CEOResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_companies_api_companies_get: {
        parameters: {
            query?: {
                is_tracked?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_api_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_by_ticker_api_companies_ticker__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_stats_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
        };
    };
    get_timeline_api_timeline_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sentiment_companies_api_dashboard_sentiment__sentiment__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sentiment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_text_api_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_ingestion_api_ingest_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_ingestion_status_api_ingest_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_feed_config_api_feeds_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedListResponse"];
                };
            };
        };
    };
    get_feeds_status_api_feeds_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_feed_api_feeds_trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerFeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_all_feeds_api_feeds_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshFeedsResponse"];
                };
            };
        };
    };
    test_feed_fetch_api_feeds_test_post: {
        parameters: {
            query: {
                feed_key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feed_statistics_api_feeds_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
